name: Workflow gradle
run-name: Workflow to deploy a Spring Boot app to Azure Web App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  call-workflow-mvn-cache-advanced:
    strategy:
      matrix:
        java-version: ['1.8', '11']
    uses: ./.github/workflows/build-mvn-cache-advanced.yml
    with:
      java: ${{ matrix.java-version }}
    secrets: inherit