name: Workflow gradle
run-name: Workflow to deploy a Spring Boot app to Azure Web App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  call-workflow-mvn-cache-advanced:
    uses: ./.github/workflows/build-mvn-cache-advanced.yml
    secrets: inherit